### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by daboyd55** [enginkizil/FeedEk#14]
Hello,

I'm having an issue where there is a delay between when a new blog post is published and when this script reflects the new post. What could be causing this? New posts are shown on the actual rss feed almost right away.

Any suggestions you could provide would be appreciated.

Thank you!

**Comment by iss85** [comment]
I'm facing the same problem as well :-\

**Comment by enginkizil** [comment]
@daboyd55 @iss85 FeedEk directly get feeds from your feed url. Could you please check if there can be delay on your feed source?
