### ISSUE TITLE
Dependency on Google Feeds API?

### ISSUE THREAD

**Issue by julien51** [enginkizil/FeedEk#22]
Hi! 
Is there any chance you'd provide a fallback to use [Superfeedr](http://superfeedr.com/) just in case the Google Feed's API gets deprecated?

**Comment by julien51** [comment]
Any news on this?

**Comment by studio1440** [comment]
Looks like Dec 1 2015 (yesterday) was the end of the Google Feed API.   Any ideas how to make this plugin work now?

**Comment by enginkizil** [comment]
Google Feed API retired on 2015 and YQL API is retired on 3th of January 2019. FeedEk v3.1.0 released and YQL API is not using anymore. Please use latest version of FeedEk v.3.1.0
@studio1440 @julien51
