### ISSUE TITLE
Can i use my own templates to show the results?

### ISSUE THREAD

**Issue by djyde** [enginkizil/FeedEk#23]
I want to show the results use my own templates like https://github.com/sdepold/jquery-rss
Could FeedEx do it as same?

**Comment by AdamHess** [comment]
It appears that the developer has abandoned the project. (there are nearly as many forks and pull requests as there are stars) 

FeedEK is basically a shim around an ajax call to a google rss api, its so simple you would be better off implementing your own version of it that uses a templating library. It would have been better practice if the developer on this project simply returned the ajax object that would allow you to add your own success handler function.  


I would highly discourage using this for professional projects.

**Comment by enginkizil** [comment]
Template option is not available yet. But FeedEk v3.2.0 just released. This version has Success and Error callback options.
You can get feed data on Success method as below and can use your own html template. 

```javascript
$('#divFeed').FeedEk({
   FeedUrl: 'https://jquery-plugins.net/rss', 
   MaxCount: 2,
   Success: function (feedItems) {
        console.log(feedItems); // List of Feed Items
        console.log(feedItems[0].title); // Title
        console.log(feedItems[0].description); // Description
   }
});
```
