### ISSUE TITLE
Request: Multiple feeds in one stream

### ISSUE THREAD

**Issue by edgarleijs** [enginkizil/FeedEk#3]
Multiple feeds in one stream

**Comment by lapid3** [comment]
There's a way for it? I need the same

**Comment by paulvangils** [comment]
If there's a way, i'd love to hear it

**Comment by enginkizil** [comment]
FeedEk v3.2.0 released and has multiple feed url support. You can use as below.

`$('#divFeed').FeedEk({
    FeedUrl : ['https://jquery-plugins.net/rss','http://rss.cnn.com/rss/cnn_topstories.rss']
});`
