### ISSUE TITLE
FeedEk not working :(

### ISSUE THREAD

**Issue by fffffelix** [enginkizil/FeedEk#32]
Hi there, I have been using FeedEk for a while but now, the plugin seems to have stopped working in all instances (on the official plugin page, and on my own page.)

http://jquery-plugins.net/FeedEk/FeedEk_demo.html - not working
http://freigeist-verlag.net/News/ - not working

Can anyone help me and tell me what the problem is?
Felix

**Comment by monofrio** [comment]
I am also having this issue, it just stop working today and the demo site is not working?

**Comment by sueboothby** [comment]
Me too. None of my feeds are showing. The demo site is not working either.

**Comment by Jckarlos92** [comment]
Another one here!

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.

**Comment by enginkizil** [comment]
YQL API is retired on 3th of January 2019. FeedEk v3.1.0 released and YQL API is not using anymore. Please use latest version of FeedEk v.3.1.0
@fffffelix @netdoctor @kingdave9 @monofrio @sueboothby
