### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by AdamHess** [enginkizil/FeedEk#34]
would love to see this located in the power repo no results showed up when i tried bower search feed | grep feedek

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.
