### ISSUE TITLE
Cannot read property 'feed' of null

### ISSUE THREAD

**Issue by madebyspark** [enginkizil/FeedEk#35]
Feeds on my site have suddenly stopped working. Get the following error:

Cannot read property 'feed' of null

**Comment by WoodyNaDobhar** [comment]
/* callback */jQuery({"responseData": null, "responseDetails": "This API is no longer available.", "responseStatus": 403})

The Google Feed API was depreciated years ago, and finally removed entirely recently.

**Comment by madebyspark** [comment]
Thx!

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.
