### ISSUE TITLE
The API is not working

### ISSUE THREAD

**Issue by Jckarlos92** [enginkizil/FeedEk#36]
Hi!

I'm using your library on one of my projects and it stopped working. I thought that  it was my error, but I checked on the official site (http://jquery-plugins.net/FeedEk/FeedEk.html) and even there is not working.

Could you please help me with this?

Thank you!

**Comment by kamaleao** [comment]
It seems that since yesterday the FeedEk stopped working. Could anyone tell me if there is any way to fix this?

**Comment by monofrio** [comment]
Having the same issue,  does anyone have a substitute plugin they recommend to fix this issue?

**Comment by kamaleao** [comment]
I've been researching and found three alternatives that seem to work:
https://developer.yahoo.com/yql/console/
http://blog.superfeedr.com/google-feed-api-alternative/
http://rss2json.com/

However, still can not implement the code. I believe it is in line 6 FeedEk.js:
$ .ajax ({url: "http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=" + def.MaxCount + "& output = json & q =" + encodeURIComponent (def.FeedUrl) + "& hl = en & callback =?", dataType: "json", success: function (data) {$ ("#" + id) .empty ();

If anyone can make it work warns us. Thank you.

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.

**Comment by enginkizil** [comment]
YQL API is retired on 3th of January 2019. FeedEk v3.1.0 released and YQL API is not using anymore. Please use latest version of FeedEk v.3.1.0 
@Jckarlos92 @kamaleao @monofrio
