### ISSUE TITLE
FeedEk Stopped Working

### ISSUE THREAD

**Issue by sueboothby** [enginkizil/FeedEk#37]
Thought I'd open a new issue. Three users have reported the same issue today:
- I am also having this issue, it just stop working today and the demo site is not working?
- Me too. None of my feeds are showing. The demo site is not working either.
- Another one here! The demo version is not working and it also stopped working on the official site

Firebug is showing the following error with an arrow pointing to the dot in "$.each":
TypeError: data.responseData is null
...cess:function(data){$('#'+idd).empty();$.each(data.responseData.feed.entries,fun...
FeedEk.js (line 1, col 545)
# 

![feedek-error](https://cloud.githubusercontent.com/assets/16123564/11544769/ad199a80-9911-11e5-8742-6d833fe052ea.jpg)

**Comment by fr8tdog** [comment]
Same issue. Believe the Google Feed API is no longer working.

**Comment by mtamony** [comment]
Yes, fr8tdog is correct. I use ZRSSFeed and it also stopped working.

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.

**Comment by fr8tdog** [comment]
The update works! Thank you!

**Comment by mtamony** [comment]
You may want to remove google api from your website instructions.

**Comment by enginkizil** [comment]
@fr8tdog @mtamony @sueboothby 
YQL API is retired on 3th of January 2019. FeedEk v3.1.0 released and YQL API is not using anymore. Please use latest version of FeedEk v.3.1.0
