### ISSUE TITLE
Google Feed API 

### ISSUE THREAD

**Issue by fr8tdog** [enginkizil/FeedEk#38]
FeedEK is no longer working. Same issues as below. Is the Google Feed API working or non-existent?

**Comment by enginkizil** [comment]
FeedEk v.3.0 with YQL API is working and now available on http://jquery-plugins.net/FeedEk/FeedEk.html 
also you can replace your existing FeedEk.js with latest http://jquery-plugins.net/FeedEk/FeedEk.min.js  
GitHub page will be updated later. Thanks.

**Comment by enginkizil** [comment]
YQL API is retired on 3th of January 2019. FeedEk v3.1.0 released and YQL API is not using anymore. Please use latest version of FeedEk v.3.1.0
@fr8tdog
