### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by somereality** [enginkizil/FeedEk#46]
Is there a different date format requirement using the latest version of FeedEK?

**Comment by BradGunnerSGT** [comment]
Are you trying to use an older RSS format? We have an RSS 0.91 feed (out of our control) and the dates come through FeedEk as null. I looked at the YQL console and using the query that FeedEk does, YQL strips out the dates since the query assumes RSS 2.0.

**Comment by somereality** [comment]
Don't recall exactly what happened - dates just got messed up after updating to the latest version.  I believe there may have been updates with moment.js that actually didn't get exposed until updating FeedEK.  I did eventually get the issue sorted out and dates rendering fine now.
