### ISSUE TITLE
Cannot read property 'rss' of null tested with multiple sources

### ISSUE THREAD

**Issue by kajapezz8** [enginkizil/FeedEk#51]
Hi,
today feedEk stop working, i'v tried to check my feed URL with your DEMO website:

http://jquery-plugins.net/FeedEk/FeedEk_demo.html

and don't work with my feed websites:

http://www.dolomitiunesco.info/feed/

or

http://opengeek.it/feed

fully compatible FEED tested with W3C validator.

Can you help me?

**Comment by BradGunnerSGT** [comment]
I can confirm that this is also happening to me. The URL that I am using this for is "http://www.utsa.edu/today/rss/top.xml".

Pulling this up in the YQP console gives me the expected output, but in Feedek it just displays the "loading" spinner and goes blank after a few seconds.

**Comment by E66666666** [comment]
Same, FeedEk stopped working completely on my [homepage](https://e66666666.github.io/homepage-alt/).

[Demo](http://jquery-plugins.net/FeedEk/FeedEk_demo.html) also seems to have died.

**Comment by jpweg1993** [comment]
Looks like YQL is having intermittent issues, my app just crapped itself for 15 minutes with similar errors ( `TypeError: null is not an object (evaluating 'data.query.results.feed')` and `Uncaught TypeError: Cannot read property 'feed' of null` ).

People have apparently been having problems for a few days now, but there's no status page for YQL so it's hard to see how much downtime there's been.

https://developer.yahoo.com/forums/#/discussion/10806/yql-connection-failures-are-not-acceptable-why-is-nobody-on-top-of-this

**Comment by E66666666** [comment]
YQL just seems rather sketchy with reliability, as it also seems much slower than Google's service, often taking >2 seconds to load feeds, where Google's was either instant or none. Don't know if it's temporary and caused by the huge increase in load because everybody and their dog is going away from Google's service, or Yahoo's just crap in general.

**Comment by enginkizil** [comment]
There are some issues on YQL, sometimes REST query had errors. But they fixed it and now it's working.

**Comment by BradGunnerSGT** [comment]
This is happening again today. Is anyone else experiencing this issue?

**Comment by zazatek** [comment]
Yes, me, everyday. 

up o/

**Comment by djavet** [comment]
Same here, everyday: https://forum.swissinfo.ch/rss/chinese_forum.html 
Any update?

**Comment by marklegault** [comment]
I don't know if this will fix your problem, but removing the ? from callback=? in FeedEK.js at the end of the url fixed the problem for me.

**Comment by E66666666** [comment]
@djavet Probably YQL cocking up again. It'll blow over.

**Comment by djavet** [comment]
Removing the ? from callback=? in FeedEK.js at the end of the url fixed the problem for me. Thx for the help.

**Comment by enginkizil** [comment]
Hello @kajapezz8 @BradGunnerSGT @E66666666 @jpweg1993  
FeedEk v3.1.0 released and YQL API is not using anymore. FeedEk can both parse RSS and Atom feeds.
You can test your feed urls on FeedEk demo page.
