### ISSUE TITLE
FeedEk not reading atom feed

### ISSUE THREAD

**Issue by eduardpaul** [enginkizil/FeedEk#52]
Hi all, 
We are using the FeedEk plugin and it works great with almost all RSS feeds, but when user configures any atom feed url it suddenly generate error. I was digging around and:
- The source that i'm using is: https://earthquake.usgs.gov/atom.php
- FeedEk/js/FeedEk.js: var YQLstr = "SELECT channel.item FROM feednormalizer WHERE output="rss_2.0" AND url ="https://earthquake.usgs.gov/atom.php" LIMIT 10"
- FeedEk/js/FeedEk.js: Yahoo's generated url is https://query.yahooapis.com/v1/public/yql?q=SELECT%20channel.item%20FROM%20feednormalizer%20WHERE%20output%3D%22rss_2.0%22%20AND%20url%20%3D%22https%3A%2F%2Fearthquake.usgs.gov%2Fatom.php%22%20LIMIT%2010&format=json&diagnostics=false&callback=

it seems that yahoo responds with zero results, but no error is generated. I also tested it with google mail atom feed (https://mail.google.com/mail/feed/atom) and the result is the same.

¿any ideas?
Thanks to all contributors, it's an excellent plugin.

**Comment by colmoneill** [comment]
I think we're having the same issue in #53 FeedEk is not dealing with ATOM feeds anymore, I think. The url you posted about @eduardpaul seems to be also an atom feed.

Did you manage to get this to work?

Thanks!

**Comment by enginkizil** [comment]
Hello,
FeedEk v3.1.0 released and FeedEk can both parse RSS and Atom feeds with this version.
@eduardpaul I just tested your atom url on FeedEk demo page and feeds are generated successfully.
