### ISSUE TITLE
TypeError: data.query.results is null

### ISSUE THREAD

**Issue by Parinapan** [enginkizil/FeedEk#53]
Hello, 
I have a little problem. 
I am trying to display a specific feed, http://feeds.feedburner.com/neueswort/ , on my homepage, but it does not work. The rss-feed is most of the times not displayed, sometimes it will appear after a long period of time and will stay for the next two reloads or so, but after that, it disappears again. In the console you can read the error message 

> TypeError: data.query.results is null

![error](https://cloud.githubusercontent.com/assets/20993151/19818148/da7a62a6-9d4e-11e6-8248-95aa8b2648a8.png)

It's pretty peculiar that the other feeds I tried out produced this error too, but they were displayed anyway.

It would be really nice if you could help me with this.

**Comment by colmoneill** [comment]
Any updates on this issue? I had been using FeedEk across a few websites for a couple of years, and they suddenly stopped being able to display feeds.

Thanks!

**Comment by colmoneill** [comment]
For clarity, this is what my console reports. Very similar to @Parinapan
![screenshot_2017-03-17_16-03-15](https://cloud.githubusercontent.com/assets/2122318/24049114/4c37900e-0b2b-11e7-96ec-ee620676c93d.png)

**Comment by colmoneill** [comment]
It seems that this only causes problems with atom feeds, but works fine with RSS.
When I paste `https://gitlab.com/colmoneill.atom` as a url into the demo page `http://jquery-plugins.net/FeedEk/FeedEk_demo.html` nothing is returned.

**Comment by colmoneill** [comment]
Still having this issue with ATOM xml feeds, has anybody found a work around?

**Comment by djavet** [comment]
Same issue issue here: https://forum.swissinfo.ch/rss/chinese_forum.html
Any update?

**Comment by marklegault** [comment]
try removing the ? at the end of the URL (callback=?), seems to have fixed the issue for me.

**Comment by djavet** [comment]
Removing the ? from callback=? in FeedEK.js at the end of the url fixed the problem for me. Thx for the help.

**Comment by enginkizil** [comment]
Hello all,
FeedEk v3.1.0 released and FeedEk can both parse RSS and Atom feeds with this version.
@colmoneill @Parinapan I just tested your atom urls on FeedEk demo page and feeds are generated successfully.
