### ISSUE TITLE
FeedEk does not genrate feeds of this url

### ISSUE THREAD

**Issue by dharam1291** [enginkizil/FeedEk#55]
http://www.ewdn.com/tag/tele/feed/%20

**Comment by colmoneill** [comment]
Yes, I believe this is similar to #53 and #52 resulting in old ATOM xls feeds not being parsed by YQL.
I'm trying to work this out, but I have had no response from @enginkizil

**Comment by enginkizil** [comment]
Hello @colmoneill @dharam1291 
FeedEk v3.1.0 released and YQL API is not using anymore. FeedEk can both parse RSS and Atom feeds.
@dharam1291 I just tested on FeedEk demo page and feeds are generated on your atom url.
