### ISSUE TITLE
Please run npm publish :)

### ISSUE THREAD

**Issue by alirobe** [enginkizil/FeedEk#59]
You've got a package.json all set up, but you still haven't published the package to NPM. 

You just need to have node installed, be logged in to NPM, and run 'npm publish'

Quick guide here: https://www.youtube.com/watch?v=BkotrAFtBM0

Thanks!

**Comment by enginkizil** [comment]
@alirobe  published to npm :) 
https://www.npmjs.com/package/feedek 
Thanks.
