### ISSUE TITLE
Custom Feed API

### ISSUE THREAD

**Issue by oleteacher** [enginkizil/FeedEk#64]
Great plugin, thank you for sharing!

Is it possible to obtain the custom feed api source code ( https://feed.jquery-plugins.net/load?url= ) to host on our own server?

Thanks.

**Comment by enginkizil** [comment]
It's free Feed Service/API, sorry can't share source code yet.

**Comment by oleteacher** [comment]
Ok, thanks. Have found another solution and very happy with it. Now no worry the API under someone else's control up and disappear.
