### ISSUE TITLE
New API ignores <media:content> and other RSS elements

### ISSUE THREAD

**Issue by usuarionuevor** [enginkizil/FeedEk#65]
While old Yahoo's API showed whats in all elements, the new API ignores some RSS elements such as:
[`<media:content>`](http://www.rssboard.org/media-rss#media-content)
and some other elements that are completely ignored too in the output.

As seen in Google's RSS for example: https://www.news.google.com/news/rss/headlines/section/topic/TECHNOLOGY

new API output: https://feed.jquery-plugins.net/load?url=https://www.news.google.com/news/rss/headlines/section/topic/TECHNOLOGY

only basic elements like description, date and title are considered @enginkizil

**Comment by enginkizil** [comment]
Thank you for your comment, but this issue is not about FeedEk plugin, its about Feed API.
I will inform you if there will be any update on FeedAPI https://jquery-plugins.net/feed-api
