### ISSUE TITLE
ERROR_ON_GETTING_FEEDS 

### ISSUE THREAD

**Issue by sjglobal** [enginkizil/FeedEk#69]
When request from : https://jquery-plugins.net/FeedEk/FeedEk_demo.html

FeedEK is getting an error with the message below:
--------------
{
data: null
errorMessage: "ERROR_ON_GETTING_FEEDS : Unable to cast object of type 'CodeHollow.FeedReader.Feeds.Rss20FeedItem' to type 'CodeHollow.FeedReader.Feeds.AtomFeedItem'."
statusCode: 400
}
--------------
I think the server-side handler(https://feed.jquery-plugins.net/load) is not parsing properly.
Full requested URL:
https://feed.jquery-plugins.net/load?url=https%3A%2F%2Ffeeds.feedburner.com%2Flm%2Frss%2Frecentlyfiled%3Fformat%3Dxml&maxCount=5&dateCulture=en&dateFormat=MM/dd/yyyy

**Comment by enginkizil** [comment]
yes there was a parsing problem, it's fixed now.
