### ISSUE TITLE
Dates as 1-1-1

### ISSUE THREAD

**Issue by TheDutchJewel** [enginkizil/FeedEk#70]
I tried FeedEk with 4 different sources. With one of them ([20 Newest Free Software Downloads - Freeware Files.com](https://www.freewarefiles.com/rss/newfiles.xml)) FeedEk has a problem with showing the correct date: it shows 1-1-1. 

Can this be fixed?

**Comment by enginkizil** [comment]
Hi, 
Because your feeds don't have **<pubDate>**  in source. Here is an example item from your feed. Your feed source must be valid for rss - atom standarts.

```
<item>
<title>Mozilla Firefox 84.0.2</title>
<description>A fast browser that includes tabbed browsing, content blocking, plugins, private browsing, more. 2021-01-06</description>
<link>https://www.freewarefiles.com/Mozilla-Firefox_program_25387.html</link>
<category>web browser, mozilla, firefox, browser, internet, web, tabbed, popup, blocker, search</category>
</item>
```
