### ISSUE TITLE
Feed no longer works.

### ISSUE THREAD

**Issue by DestructiveBurn** [enginkizil/FeedEk#71]
Hello, I would've rather made this more private but I wanted to let you know, your FeedEk is no longer working because it's connected to https://jquery-plugins.net/

As of right now from this message, it's offline and the API no longer works.  I would like to ask if there is a way I can use my own server to replace the job.  "https://feed.jquery-plugins.net/load?url="

Hopefully, it's just offline for maintenance but kinda sucks that I need to rely on another server.

**Comment by enginkizil** [comment]
Hello, It's offline because for unexpected maintenance. Now API online and it's working.
Thank you.

**Comment by DestructiveBurn** [comment]
Yup!  Indeed it is.  Thanks ;)
