### ISSUE TITLE
Plugin does not work since yesterday, API down?

### ISSUE THREAD

**Issue by Efekent** [enginkizil/FeedEk#79]
Hello @enginkizil 

First of all, thank you for this great script!

I think API is down, the plugin does not work anymore, it would be great if you could fix it.

**Comment by Efekent** [comment]
It started working the next day, closing the issue.

**Comment by Efekent** [comment]
Same issue started yesterday again, could you please look in to it?
Thanks.

**Comment by enginkizil** [comment]
could you please chack again? issue resolved.

**Comment by Efekent** [comment]
@enginkizil thank you for vast response! It is working again.
